-- Local DB bootstrap after Hibernate ddl-auto.
-- Timestamps (created_at / updated_at) are owned by Spring Data JPA Auditing
-- (BaseEntity / CreatedAtEntity). No DB DEFAULT / ON UPDATE restoration here.
